### ISSUE TITLE
Error written to stderr: "This UTF-8 encoding can't convert to UTF-16:"

### ISSUE THREAD

**Issue by halfak** [rfk/pyenchant#58] opened 2015-09-13 15:18 UTC
This seems to happen when unicode chars > 2**16 - 1 are checked against a dictionary.  

```
$ python
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> d = enchant.Dict("en")
>>> d.check("test")
True
>>> chr(2**16 - 1)
'\uffff'
>>> d.check(chr(2**16 - 1))
False
>>> d.check(chr(2**16))
This UTF-8 encoding can't convert to UTF-16:
𐀀[goofy unicode char here]
False
>>> d.check(chr(2**16 + 1))
This UTF-8 encoding can't convert to UTF-16:
𐀀[goofy unicode char here]𐀁
False
>>> chr(2**16)
'𐀀𐀀[goofy unicode char here]'
```

This stderr should be silenced.  I've been using this function to perform cleanup before running dictionary checks.  It could probably be incorporated into pyenchant:

```
def utf16_cleanup(token):
    return "".join(c if ord(c) < 2**16 else REPLACEMENT_CHAR
                   for c in token)
```

**Comment by halfak** [comment] 2015-09-13 15:56
It looks like [EnchantStr](https://github.com/rfk/pyenchant/blob/master/enchant/utils.py#L117) is the right place to do this.  There's a function there specifically used to "Encode this string into a form usable by the enchant C library." 

```
    def encode(self):
        """Encode this string into a form usable by the enchant C library."""
        if str is unicode:
          return str.encode(self,"utf-8")
        else:
          return self
```

We could change this function to something like this:

```
    def encode(self):
        """Encode this string into a form usable by the enchant C library."""
        if str is unicode:
          utf16_safe_string = "".join(c if ord(c) < 2**16 else REPLACEMENT_CHAR
                                      for c in self)
          return str.encode(utf16_safe_string, "utf-8")
        else:
          return self
```

**Comment by rfk** [comment] 2015-09-13 23:05
Thanks for the report @halfak.  I wonder if this is expected behavior from the underlying spellcheck engine, or is specific to a particular platform.  What is the value of `d.provider` in this test?

**Comment by halfak** [comment] 2015-09-14 18:54
```
$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> d = enchant.Dict("en")
>>> d.provider
<Enchant: Myspell Provider>
>>> enchant.__version__
'1.6.6'
```

I should mention that I am running Ubuntu 14.04 x64 and fully updated.

**Comment by halfak** [comment] 2015-09-21 15:43
I should note that I'm getting the same behavior in Debian Jessie.

**Comment by jwilk** [comment] 2015-12-12 18:22
The error message comes from Hunspell:
https://sources.debian.net/src/hunspell/1.3.3-3/src/hunspell/csutil.cxx/?hl=179#L178

**Comment by rfk** [comment] 2015-12-18 03:22
So my concern here is, I don't think we should insert replacement characters for *all* providers if this problem is specific to just one provider.  Perhaps we can use the value of `d.provider` to choose at runtime, whether to use the existing EnchantStr class or a utf16-safety-checking subclass?

**Comment by halfak** [comment] 2015-12-21 15:57
Totally make sense.  However, I don't think that the message is limited to hunspell.  I might be misunderstanding though.  Here's what I see.  

```
$ python
Python 3.4.3 (default, Jul 28 2015, 18:20:59) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> d = enchant.Dict("en")
>>> d.provider
<Enchant: Myspell Provider>
>>> d.check(chr(2**16))
This UTF-8 encoding can't convert to UTF-16:
𐀀
False
>>> d = enchant.Dict("he")
>>> d.provider
<Enchant: Hspell Provider>
>>> d.check(chr(2**16))
True
```

**Comment by jwilk** [comment] 2016-01-27 11:58
This is confusing, because `d.provider` says *Myspell* even when the actual backend is Hunspell.
I couldn't find the warning message in question in the MySpell source. In fact, I believe MySpell didn't support UTF-8 at all.

**Comment by rfk** [comment] 2016-02-15 09:22
> This is confusing, because d.provider says Myspell even when the actual backend is Hunspell.

Yeah, the underlying enchant lib is a bit weird in this regard, the "myspell" provider is actually a local copy of hunspell that's built alongside the enchant library.

**Comment by rfk** [comment] 2016-07-04 10:49
IIUC this should be fixed on master now

**Closed by rfk** 2016-07-04 10:49 UTC
